<?php
return [
    'email_footer' => 'Do not reply any email to this email address. This email sent automatically by our system. ',
    'login_message' => 'Please login to start your session',
    'text_forgot_password' => 'Forgot the password ?',
    'page_title_login' => 'Login Panel',
    'page_title_forgot' => 'Forgot Password',
    'forgot_message' => 'Enter your email address, to request password',
    "forgot_text_try_again" => "Try login again ?",
    'page_title_multi_authentication' => 'Multi Authentication',
    'multi_authentication_message' => 'We send Authentication Code to your email. Please, enter code here',
    'multi_authentication_text_try_again' => "Try login again ?",
    'multi_authentication_code_incorrect' => "Code is not correct. please enter code again.",
    'text_no_notification' => "You have 0 notifications",
    'text_view_all_notification' => 'View All',
    'label_button_profile' => "Profile",
    'filter_dialog_title' => 'Advanced Sort & Filter',
    'there_is_no_option' => 'There is no any options setting for this inputType',
    'no' => 'No.',

    'text_enter_the_password' => 'Enter your password to retrieve your session',
    'text_or_sign_in' => 'Or sign in as a different user',
    'text_default_add_new_module' => 'Add New :module',
    'text_default_list_module' => 'List :module',
    'text_default_help_password' => 'Minimum 5 characters. Please leave empty if you did not change the password.',
    'text_default_help_upload' => 'File types support : JPG, JPEG, PNG, GIF, BMP',
    'text_default_help_number' => 'You can only enter the number only',
    'text_default_help_email' => 'Please enter a valid email address',
    'text_default_help_text' => 'You can only enter the letter only',
    'text_default_help_url' => 'Please enter a valid URL',
    'text_dashboard' => 'Dashboard',
    'text_delete' => 'Delete',
    'text_prefix_option' => '** Please select a',
    'text_loading' => 'Please wait loading...',

    'message_after_logout' => 'Thank You, See You Later !',
    'message_not_valid_reset_token' => 'This url is not valid any more !',
    'message_expired_reset_token' => 'This token has been expired !',
    'password_reset_not_matching' => 'Confirmation password is not matching entered password !',
    'password_changed_successfully' => 'Your password has been successfully changed',
    'message_forgot_password' => 'We have sent a request to your email, check inbox or spambox !',

    'page_not_found' => 'Oops! Page Not Found',
    'page_not_found_text' => 'We are unable search the page that you are looking for.',
    'page_not_found_tips' => '* Please make sure the URL is correct<br/>
                * Please make sure the font capitalizing is correct because case sensitive<br/>
                * Maybe the page that you are looking for has been deleted by Admin<br/>
                * You can go back by click Back Button at browser<br/>',

    'log_try_view' => 'Try view the data :name at :module',
    'log_try_edit' => 'Try edit the data :name at :module',
    'log_try_add' => 'Try add data at :module',
    'log_try_add_save' => 'Try add the data :name data at :module',
    'log_try_delete' => 'Try delete the :name data at :module',
    'log_try_delete_selected' => 'Try delete selected at :module',
    'log_try_delete_image' => 'Try delete the image of :name data at :module',
    'log_try_update' => 'Try update the :name data at :module',
    'log_add' => 'Add New Data :name at :module',
    'log_update' => 'Update data :name at :module',
    'log_delete' => 'Delete data :name at :module',
    'log_delete_image' => 'Delete the image of :name at :module',
    'log_login' => ':email login with IP Address :ip',
    'log_forgot' => 'Someone with IP :ip request a password for :email',
    'log_multi_authentication' => 'Someone with IP :ip request multi authentication for :email',
    'log_logout' => ':email logout',

    'alert_delete_selected' => 'Are you sure want to delete all selected data ?',
    'alert_delete_selected_success' => 'Delete selected success !',
    'alert_bulk_action_button' => 'Are you sure want to',
    'alert_action' => 'You have :action successfully !',
    'alert_add_data_success' => 'The data has been added !',
    'alert_add_data_failed' => 'Failed to save the data !',
    'alert_update_data_success' => 'The data has been updated !',
    'alert_update_seo_success' => 'The SEO has been updated !',
    'alert_update_data_failed' => 'Failed to update the data',
    'alert_delete_data_success' => 'Delete the data success !',
    'alert_want_to_logout' => 'Do you want to logout ?',
    'alert_warning' => "Oops",
    'alert_danger' => 'Something went wrong ....',
    'alert_success' => 'Wow, good job...',
    'alert_info' => 'Information',
    'alert_primary' => 'Information',
    'alert_session_expired' => 'Your session was expired, please login again !',
    'alert_password_wrong' => 'Sorry your password is wrong !',
    'alert_required' => 'Please make sure to fill out all the required fields correctly',
    'alert_error_ajax' => 'Okay, It is embarasing, something went wrong, we will fix it soon !',
    'alert_validation_error' => 'Please fill out the form correctly : :error',
    'alert_select_a_data' => 'Please select at least one data!',

    'add_data_page_title' => 'Add :module',
    'edit_data_page_title' => 'Edit :module',
    'detail_data_page_title' => 'Detail :module',

    'default_module_description' => 'Data List',

    'delete_description_confirm' => "You will not be able to recover this record data!",
    'delete_title_confirm' => "Are you sure ?",

    'action_show_data' => 'Show Data',
    'action_add_data' => 'Add Data',
    'action_delete_selected' => 'Delete Selected',

    'action_label' => 'Action',
    'action_detail_data' => 'Detail Data',
    'action_edit_data' => 'Edit Data',
    'action_delete_data' => 'Delete',

    'button_cancel' => 'Cancel',
    'button_add' => 'Add Data',
    'button_edit' => 'Edit Data',
    'button_back' => 'Back',
    'button_save' => 'Save',
    'button_save_more' => 'Save & Add More',
    'button_import' => 'Import Data',
    'button_export' => 'Export Data',
    'button_filter' => 'Sort & Filter',
    'button_close' => 'Close',
    'button_submit' => 'Submit',
    'button_logout' => 'Logout',
    'button_sign_in' => 'Sign In',
    'button_selected_action' => 'Bulk Actions',
    'button_download_file' => 'Download file',
    'button_reset' => 'Reset',
    'button_add_to_table' => 'Add To Table',

    'export_dialog_title' => "Export Data",
    'export_dialog_filename' => 'File Name',
    'export_dialog_help_filename' => 'You can rename the filename according to your whises',
    'export_dialog_maxdata' => "Max Data",
    'export_dialog_help_maxdata' => 'Minimum 1 and maximum 100,000 rows per export session',
    'export_dialog_columns' => 'Columns',
    'export_dialog_format_export' => 'Format Export',
    'export_dialog_show_advanced' => 'Show Advanced Export',
    'export_dialog_page_size' => 'Page Size',
    'export_dialog_set_default' => 'Set As Default Paper Size',
    'export_dialog_page_orientation' => 'Page Orientation',

    'import_page_title' => 'Import Data :module',
    'dashboard_default_text' => 'Welcome to the dashboard of :appname',
    'form_back_to_list' => 'Back To List Data :module',
    'not_logged_in' => 'You are not logged in !',
    'menu_navigation' => "Navigation",
    'table_data_not_found' => "No Data Avaliable",
    "notice_delete_file_upload" => "* If you want to upload other file, please first delete the file.",
    "file_broken" => "Oops looks like File was Broken !. Click Delete and Re-Upload.",

    'denied_access' => 'Sorry you do not have privilege to access this area !',
    'denied_update' => 'Sorry you do not have privilege to update the data !',
    'denied_create' => 'Sorry you do not have privilege to create the data !',
    'denied_delete' => 'Sorry you do not have privilege to delete the data !',

    'user_image' => 'User Image',
    'online' => 'Online',
    'controller_route_404' => 'Controller / Route Not Found',
    'home' => 'Home',
    'Notifications' => 'Notifications',
    'Privileges' => 'Privileges',
    'Privileges_Roles' => 'Privileges Roles',
    'Add_New_Privilege' => 'Add New Privilege',
    'List_Privilege' => 'List Privilege',
    'add_user' => 'Add User',
    'List_users' => 'List Users',
    'Menu_Management' => 'Menu Management',
    'Add_New_Setting' => 'Add New Setting',
    'Add_New_Module' => 'Add New Module',
    'List_Module' => 'List Module',
    'Add_New_Statistic' => 'Add New Statistic',
    'List_Statistic' => 'List Statistic',
    'Add_New_API' => 'Add New API',
    'API_Generator' => 'API Generator',
    'Statistic_Builder' => 'Statistic Builder',
    'Module_Generator' => 'Module Generator',
    'Module_Status' => 'Module Status',
    'settings' => 'Settings',
    'Users_Management' => 'Users Management',
    'list_API' => 'List API (Documentation)',
    'Generate_Screet_Key' => 'Generate Secret Key',
    'enter_key' => 'Enter Key',
    'enter_value' => 'Enter Value',
    'Add_New_Email' => 'Add New Email',
    'List_Email_Template' => 'List Email Template',
    'Email_Templates' => 'Email Templates',
    'Log_User_Access' => 'Log User Access',
    'SUPERADMIN' => 'SUPERADMIN',
    'labels_translation' => 'Lables Translation',
    'pages_and_forms' => 'Pages And Forms',

    'click_here' => 'Click here',

    /*
     * this is for html direction to use in html and css classes like :
     * pull-left , pull-right , text-right ...
     * to make it easy to use the the view for rtl langs .
     * unless your language use right-to-left direction , you should keep it as it is :
     */
    'right' => 'right',
    'left' => 'left',

    'all_rights_reserved' => 'All Rights Reserved',
    'copyright' => 'Copyright',
    'powered_by' => 'Powered by',

    'notification_you_have' => 'You Have',
    'notification_notification' => 'Notifications',
    'notification_new' => 'You have a new notification !',

    'login_register_style' => 'Login Register Style',
    'email_setting' => 'Email Setting',
    'application_setting' => 'Application Setting',

    // table filter & sort
    'filter_select_operator_type' => 'Select Operator Type',
    'filter_ascending' => 'ASCENDING',
    'filter_descending' => 'DESCENDING',
    'filter_equal_to' => '=(Equal to)',
    'filter_like' => 'LIKE',
    'filter_not_like' => 'NOT LIKE',
    'filter_greater_than_or_equal' => '>= (Greater Than or Equal)',
    'filter_less_than_or_equal' => '<= (Less Than or Equal)',
    'filter_less_than' => '< (Less Than)',
    'filter_greater_than' => '> (Greater Than)',
    'filter_not_equal_to' => '!= (Not Equal to)',
    'filter_in' => 'IN',
    'filter_not_in' => 'NOT IN',
    'filter_between' => 'BETWEEN',
    'filter_empty_or_null' => 'Empty ( or Null)',
    'filter_sort_ascending' => 'Sort ascending',
    'filter_sort_descending' => 'Sort Descending',
    'filter_eg' => 'e.g',
    'filter_lorem_ipsum' => 'Lorem ipsum',
    'filter_lorem_ipsum_dolor_sit' => ' Lorem,Ipsum,Dolor Sit',
    'filter_search' => 'Search',
    'filter_from' => 'from',
    'filter_to' => 'to',
    'filter_sorting' => 'Sorting',
    'filter_rows_total' => 'Total rows',
    'filter_rows_to' => 'to',
    'filter_rows_of' => 'of',

    // confirmation
    'confirmation_yes' => 'Yes!',
    'confirmation_no' => 'No',

    //filemanager
    'chose_an_image' => 'Choose an image ',
    'chose_an_file' => 'Choose a file ',

    //forms & landing pages
    'Pages' => 'Pages',
    'Forms' => 'Forms',

    //action confirmation
    'confirmation_title' => 'Confirmation',
    'confirmation_text' => 'Are you sure want to do this action?',
    'confirmButtonText' => 'Yes',

    // privilege
    'privileges_name' => 'Privilege Name',
    'privileges_super_admin' => 'Super Admin',
    'privileges_standart_user' => 'Standart user',
    'privileges_ID' => 'ID',
    'set_as_superadmin' => 'Set as Superadmin',
    'chose_theme_color_select' => '** Choose Backend Theme Color',
    'chose_theme_color' => ' Theme Color',
    'privileges_configuration' => 'Privileges Configuration',
    'privileges_module_list_no' => 'No.',
    'privileges_module_list_mod_names' => 'Module\'s Name',
    'privileges_module_list_view' => 'View',
    'privileges_module_list_create' => 'Create',
    'privileges_module_list_read' => 'Read',
    'privileges_module_list_update' => 'Update',
    'privileges_module_list_delete' => 'Delete',

    //datamodal
    'datamodal_select' => 'Select',
    'datamodal_search_and_enter' => 'Search and enter...',
    'datamodal_enter_to_search' => 'Enter to search',
    'datamodal_browse_data' => 'Browse Data',
    'datamodal_browse_file' => 'Browse File',

    //child
    'table_detail' => 'Table Detail',
    'your_file_size_is_too_big' => 'Your file size is too big',
    'save_changes' => 'Save Changes',
    'please_complete_the_form' => 'Please complete the form !',
    'this_field_is_required' => 'This field is required',
    'text_form' => 'Form',
    "your_file_extension_is_not_allowed " => "Your file extension is not allowed !",

    "filemanager" => [
        'Select' => 'Select',
        'Deselect_All' => 'Deselect All',
        'Select_All' => 'Select All',
        'Erase' => 'Erase',
        'Open' => 'Open',
        'Confirm_del' => 'Are you sure you want to delete?',
        'All' => 'All',
        'Files' => 'Files',
        'Images' => 'Images',
        'Archives' => 'Archives',
        'Error_Upload' => 'The uploaded file exceeds the max size allowed.',
        'Error_extension' => 'File extension is not allowed.',
        'Upload_file' => 'Upload',
        'Filters' => 'Filters',
        'Videos' => 'Videos',
        'Music' => 'Music',
        'New_Folder' => 'New Folder',
        'Folder_Created' => 'Folder correctly created',
        'Existing_Folder' => 'Existing folder',
        'Confirm_Folder_del' => 'Are you sure to delete the folder and all the elements in it?',
        'Return_Files_List' => 'Return to files list',
        'Preview' => 'Preview',
        'Download' => 'Download',
        'Insert_Folder_Name' => 'Insert folder name:<br/> <small>Note: It should preferably be in English, If not will be translated it into English automatically.</small>',
        'Root' => 'root',
        'Rename' => 'Rename',
        'Rename_with_note' => 'Rename <br/> <small>Note: It should preferably be in English, If not will be translated it into English automatically.</small>',
        'Edit_alt_text'=>'Edit Alternate Text',
        'Empty_alt_text'=>'Empty Alternate Text',
        'Edit_alt_text_done'=>'Edit Alternate Text Done.',
        'Back' => 'back',
        'View' => 'View',
        'View_list' => 'List view',
        'View_columns_list' => 'Columns list view',
        'View_boxes' => 'Box view',
        'Toolbar' => 'Toolbar',
        'Actions' => 'Actions',
        'Rename_existing_file' => 'The file is already existing',
        'Rename_existing_folder' => 'The folder is already existing',
        'Empty_name' => 'The name is empty',
        'Text_filter' => 'text filter',
        'Swipe_help' => 'Swipe the name of file/folder to show options',
        'Upload_base' => 'Base upload',
        'Upload_base_help' => "Drag & Drop files(modern browsers) or click in upper button to Add the file(s) and click on Start upload. When the upload is complete, click the 'Return to files list' button.",
        'Upload_base_help2' => "Drag & Drop files(modern browsers) or click in upper button to Add the file(s) to upload Files. <br/> <strong>Note: The files names should preferably be in English, If not will be translated it into English automatically.</strong>",
        'Upload_add_files' => 'Add file(s)',
        'Upload_start' => 'Start upload',
        'Upload_error_messages' => array(
            1 => 'The uploaded file exceeds the upload_max_filesize directive in php.ini',
            2 => 'The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form',
            3 => 'The uploaded file was only partially uploaded',
            4 => 'No file was uploaded',
            6 => 'Missing a temporary folder',
            7 => 'Failed to write file to disk',
            8 => 'A PHP extension stopped the file upload',
            'post_max_size' => 'The uploaded file exceeds the post_max_size directive in php.ini',
            'max_file_size' => 'File is too big',
            'min_file_size' => 'File is too small',
            'accept_file_types' => 'Filetype not allowed',
            'max_number_of_files' => 'Maximum number of files exceeded',
            'max_width' => 'Image exceeds maximum width',
            'min_width' => 'Image requires a minimum width',
            'max_height' => 'Image exceeds maximum height',
            'min_height' => 'Image requires a minimum height',
            'abort' => 'File upload aborted',
            'image_resize' => 'Failed to resize image',
        ),
        'Upload_url' => 'From url',
        'Type_dir' => 'dir',
        'Dimension' => 'Dimension',
        'Size' => 'Size',
        'Date' => 'Date',
        'Filename' => 'Filename',
        'Operations' => 'Operations',
        'Date_type' => 'y-m-d',
        'OK' => 'OK',
        'Cancel' => 'Cancel',
        'Sorting' => 'sorting',
        'Show_url' => 'Show URL',
        'Extract' => 'Extract here',
        'File_info' => 'file info',
        'Edit_image' => 'Edit image',
        'Duplicate' => 'Duplicate',
        'Folders' => 'Folders',
        'Copy' => 'Copy',
        'Cut' => 'Cut',
        'Paste' => 'Paste',
        'CB' => 'CB', // clipboard
        'Paste_Here' => 'Paste to this directory',
        'Paste_Confirm' => 'Are you sure you want to paste to this directory? This will overwrite existing files/folders if encountered any.',
        'Paste_Failed' => 'Failed to paste file(s)',
        'Clear_Clipboard' => 'Clear clipboard',
        'Clear_Clipboard_Confirm' => 'Are you sure you want to clear the clipboard?',
        'Files_ON_Clipboard' => 'There are files on the clipboard.',
        'Copy_Cut_Size_Limit' => 'The selected files/folders are too big to %1$s. Limit: %2$d MB/operation', // %1$s = cut or copy, %2$d = max size
        'Copy_Cut_Count_Limit' => 'You selected too many files/folders to %1$s. Limit: %2$d files/operation', // %1$s = cut or copy, %2$d = max count
        'Copy_Cut_Not_Allowed' => 'You are not allowed to %1$s %2$s.', // %12$s = cut or copy, %2$s = files or folders
        'Image_Editor_No_Save' => 'Could not save image',
        'Image_Editor_Exit' => "Exit",
        'Image_Editor_Save' => "Save",
        'Zip_No_Extract' => 'Could not extract. File might be corrupt.',
        'Zip_Invalid' => 'This extension is not supported. Valid: zip, gz, tar.',
        'Dir_No_Write' => 'The directory you selected is not writable.',
        'Function_Disabled' => 'The %s function has been disabled by the server.', // %s = cut or copy
        'File_Permission' => 'File permission',
        'File_Permission_Not_Allowed' => 'Changing %s permissions are not allowed.', // %s = files or folders
        'File_Permission_Recursive' => 'Apply recursively?',
        'File_Permission_Wrong_Mode' => "The supplied permission mode is incorrect.",
        'User' => 'User',
        'Group' => 'Group',
        'Yes' => 'Yes',
        'No' => 'No',
        'Lang_Not_Found' => 'Could not find the language.',
        'Lang_Change' => 'Change the language',
        'File_Not_Found' => 'Could not find the file.',
        'File_Open_Edit_Not_Allowed' => 'You are not allowed to %s this file.', // %s = open or edit
        'Edit' => 'Edit',
        'Edit_File' => "Edit file's content",
        'File_Save_OK' => "File successfully saved.",
        'File_Save_Error' => "There was an error while saving the file.",
        'New_File' => 'New File',
        'No_Extension' => 'You have to add a file extension.',
        'Valid_Extensions' => 'Valid extensions: %s', // %s = txt,log etc.

        'SERVER ERROR' => "SERVER ERROR",
        'forbidden' => "Forbidden",
        'wrong path' => "Wrong path",
        'wrong name' => "Wrong name",
        'wrong extension' => "Wrong extension",
        'wrong option' => "Wrong option",
        'wrong data' => "Wrong data",
        'wrong action' => "Wrong action",
        'wrong sub-action' => "Wrong sub-actio",
        'no action passed' => "No action passed",
        'no path' => "No path",
        'no file' => "No file",
        'view type number missing' => "View type number missing",
        'Not enough Memory' => "Not enough Memory",
        'max_size_reached' => "Your image folder has reach its maximale size of %d MB.", //%d = max overall size
        'B' => "B",
        'KB' => "KB",
        'MB' => "MB",
        'GB' => "GB",
        'TB' => "TB",
        'total size' => "Total size",

    ],
    #
    'clear_logs' => 'Clear All Logs',
    'def_img_quality' => 'This field specifies the quality of the image after uploading (The image quality will decrease as we decrease the input value and vice versa)',
    'notifications_activity' => 'This field determines whether notifications are enabled or not (not enabled by default)',
    'default_image' => 'This image will appear if the image field is empty',
    'language_setting' => 'CMS Language Setting',
    'activate_tow_languages' => 'Activate Arabic and English Language in CMS',
    'default_language' => 'This field determines the default language in CMS',
    'block_ip_in_hours_helper' => 'This field determines how much time you will block the IP address after n number of failed login tries in hours',
    'max_failed_login_trying_helper' => 'This feild determines the maximum number of failed login tries before blocking the user',
    'block_users_setting' => 'Block Users Setting',
    'login_block_msg' => 'Sorry, it seems like you have exceeded the maximum number of login attempts. For security reasons, you have been temporarily blocked. Please try again later or contact our support team if you need assistance unblocking you. Thank you.',
    'search_for_key_values' => 'Search for keys or values',
    'activate_label' => 'Activate Label',
    'deactivate_label' => 'Deactivate Label',
    'has_images' => 'Has List Images',
    'model_images' => 'Images',

    'file_support_ext' => 'File support only jpg,png,gif, Max 10 MB',
    'enter_lang_values' => 'Enter Values',
    'enter_lang_key' => 'Enter Key',
    'Website_Languages' => 'Website Languages',

    // setting labels
    'email_sender' => 'Email Sender',
    'mail_driver' => 'Mail Driver',
    'smtp_host' => 'SMTP Host',
    'smtp_port' => 'SMTP Port',
    'smtp_username' => 'SMTP Username',
    'smtp_password' => 'SMTP Password',
    'application_name' => 'Application Name',
    'default_paper_size' => 'Default Paper Print Size',
    'uploaded_default_image' => 'Default Image',
    'image_compression_value' => 'Image Compression Value',
    'favicon' => 'Favicon',
    'api_debug_mode' => 'API Debug Mode',
    'google_api_key' => 'Google API Key',
    'google_fcm_key' => 'Google FCM Key',
    'activate_notifications' => 'Activate Notifications',
    'default_cms_language' => 'Default CMS Language',
    'block_ip_in_hours' => 'Block IP address In Hours',
    'max_failed_login_trying' => 'Maximum Attempts',
    'no_use_cms_prefix' => 'Do not use cms_* as prefix on your tables name',
    'module_slug_expression' => 'Please alpha numeric only, without space instead _ and or special character',
    'ask_create_modules_menu' => 'Also create menu for this module',
    'create_modules_menu' => 'If you check this, we will create the menu for this module',
    'title_field_candidate' => 'Title Field Candidate',

    'successfully_save_settings' => 'Your setting has been saved !',
    'Module_Blocked_IPS' => 'Block List',

    'Backup_Restore_DB' => 'Backup & Restore DB',
    'restore_db' => 'Restore',
    'delete_db' => 'Delete',
    'make_backup' => 'Create a new Backup',
    'recaptcha_site_key' => 'reCAPTCHA site key',
    'recaptcha_secret_key' => 'reCAPTCHA secret key',
    'success_add_backup' => 'The backup has been added successfully',
    'error_add_backup' => 'Some thing went wrong while adding backup !',
    'action_set_seo' => 'Set SEO',
    'backup_file_size' => 'Size',
    'reCAPTCHA_setting' => 'reCaptcha Settings',

    'alert_recaptcha' => 'There was an error with the reCAPTCHA. Please try again later',
    'menus_configuration'=>'Menus Configuration',

];
