<?php
return [
    'email_footer' => 'هذه رسالة تلقائية ، الرجاء عدم الرد مباشرة على هذا البريد الإلكتروني .',
    'login_message' => 'الرجاء تسجيل الدخول',
    'text_forgot_password' => 'نسيت كلمة المرور ?',
    'page_title_login' => 'تسجيل الدخول',
    'page_title_forgot' => 'نسيت كلمة المرور',
    'forgot_message' => 'ادخل بريدك الإلكتروني لاستعادة كلمة المرور',
    "forgot_text_try_again" => " حاول تسجيل الدخول مرة اخرى ?",
    'page_title_multi_authentication' => 'مصادقة',
    'multi_authentication_message' => 'قمنا بإرسال كود المصادقة إلي بريدك الإلكتروني. أرجو ادخاله هنا.',
    'multi_authentication_text_try_again' => " حاول تسجيل الدخول مرة اخرى ?",
    'multi_authentication_code_incorrect' => "كود المصادقة غير صحيح . أدخل الكود مرة أخرى.",
    'text_no_notification' => "لا توجد لديك تنبيهات",
    'text_view_all_notification' => 'عرض الكل',
    'label_button_profile' => "الملف الشخصي",
    'filter_dialog_title' => 'فرز متقدم',

    'Default CMS Language' => 'اللغة الافتراضية',
    'Activate Tow Languages' => 'تفعيل اللغتين',

    'text_enter_the_password' => 'فضلا ادخل كلمة المرور لاستعادة جلسة العمل',
    'text_or_sign_in' => 'او سجل الدخول بمستخدم مختلف',
    'text_default_add_new_module' => 'اضافة :module جديد',
    'text_default_list_module' => 'عرض :module',
    'text_default_help_password' => '٥ احرف فما فوق ، اترك الحقل فارغا اذا لا تريد تغيير كلمة المرور',
    'text_default_help_upload' => 'الملفات المدعومة : JPG, JPEG, PNG, GIF, BMP',
    'text_default_help_number' => 'ادخل ارقام فقط',
    'text_default_help_email' => 'صيغة البريد الإلكتروني غير صحيحة',
    'text_default_help_text' => 'فضلا ادخل احرف فقط',
    'text_default_help_url' => 'فضلا ادخل رابط إلكتروني صحيح',
    'text_dashboard' => 'الرئيسية',
    'text_prefix_option' => '** فضلا اختر',
    'text_loading' => 'فضلا الانتظار جاري التحميل ...',

    'message_after_logout' => 'شكرا لك ، نراك لاحقا !',
    'message_forgot_password' => 'تم ارسال الطلب إلى بريدك الإلكتروني !',

    'page_not_found' => 'عفوا الصفحة غير موجودة',
    'page_not_found_text' => 'لم يتم العثور على الصفحة التي تبحث عنها.',
    'page_not_found_tips' => '* تآكد من ان الرابط صحيح<br/>
                * تآكد من الاحرف فهي حساسة للحالة<br/>
                * ربما تم حذف الصفحة<br/>
                * يمكنك العودة للخلف وتجربة رابط اخر<br/>',

    'log_try_view' => 'حاول عرض  :name في :module',
    'log_try_edit' => 'حاول تعديل بيانات :name في :module',
    'log_try_add' => 'حاول اضافة بيانات في :module',
    'log_try_add_save' => 'حاول اضافة بيانات :name data في :module',
    'log_try_delete' => 'حاول حذف :name data في :module',
    'log_try_delete_selected' => 'حاول حذف في :module',
    'log_try_delete_image' => 'حاول حذف الصور من :name data في :module',
    'log_try_update' => 'حاول تعديل الاسم :name data في :module',
    'log_add' => 'اضافة بيانات جديدة :name في :module',
    'log_update' => 'تعديل :name في :module',
    'log_delete' => 'حذف :name في :module',
    'log_delete_image' => 'حذف الصورة :name في :module',
    'log_login' => ':email سجل دخل من رقم آيبي :ip',
    'log_forgot' => 'شخصا ما من الآيبي :ip طلب اعاة تعيين كلمة المرور :email',
    'log_multi_authentication' => 'شخصا ما من الآيبي :ip طلب المصادقة عن طريق البريد الإلكتروني :email',
    'log_logout' => ':email تسجيل خروج',

    'alert_delete_selected' => 'هل آنت متآكد من حئف كافة البيانات المحددة ?',
    'alert_delete_selected_success' => 'البيانات المحددة تم حذفها بنجاح !',
    'alert_action' => 'تم :action بنجاح !',
    'alert_add_data_success' => 'تم اضافة البيانات !',
    'alert_add_data_failed' => 'فشل حفظ البيانات !',
    'alert_update_data_success' => 'تم تحديث البيانات !',
    'alert_update_seo_success' => 'تم تحديث بيانات ال SEO',
    'alert_update_data_failed' => 'فشل تحديث البيانات',
    'alert_delete_data_success' => 'تم حذف البيانات !',
    'alert_want_to_logout' => 'هل أنت متأكد من تسجيل الخروج ?',
    'alert_warning' => "عفوا ..",
    'alert_danger' => 'حدث خطأ ما  ....',
    'alert_success' => 'تم بنجاح ...',
    'alert_info' => 'معلومات',
    'alert_primary' => 'معلومات',
    'alert_session_expired' => 'عفوا انتهت جلسة العمل ، فضلا اعد تسجيل الدخول !',
    'alert_password_wrong' => 'عفو كلمة المرور خاطئة !',
    'alert_required' => 'فضلا اكمل كافة الحقول المطلوبة',
    'alert_error_ajax' => 'عفوا لقد حصل خطا ما ، سيتم حل المشكلة في اقرب وقت ممكن !',
    'alert_validation_error' => 'فضلا اكمل الحقول بشكل صحيح : :error',

    'add_data_page_title' => 'اضافة :module',
    'edit_data_page_title' => 'تعديل :module',
    'detail_data_page_title' => 'تفاصيل :module',

    'default_module_description' => 'جدول البيانات',

    'delete_description_confirm' => "لا يمكنك التراجع عن عملية الحذف !",
    'delete_title_confirm' => "هل آنت متأكد ؟",

    'action_show_data' => 'عرض البيانات',
    'action_add_data' => 'اضافة بيانات',
    'action_delete_selected' => 'حذف المحدد',

    'action_label' => 'الاجراء',
    'action_detail_data' => 'التفاصيل',
    'action_edit_data' => 'تعديل',
    'action_delete_data' => 'حذف',

    'button_cancel' => 'إلغاء',
    'button_add' => 'اضافة بيانات',
    'button_edit' => 'تعديل بيانات',
    'button_back' => 'للخلف',
    'button_save' => 'حفظ',
    'button_save_more' => 'حفظ واضافة المزيد',
    'button_import' => 'استيراد البيانات',
    'button_export' => 'تصدير البيانات',
    'button_filter' => 'الفرز والتصفية',
    'button_close' => 'اغلاق',
    'button_submit' => 'حفظ',
    'button_logout' => 'تسجيل الخروج',
    'button_sign_in' => 'تسجيل الدخول',
    'button_selected_action' => 'الاجراء الجماعي',
    'button_download_file' => 'تنزيل الملف',
    'button_reset' => 'اعادة تعيين',
    'button_add_to_table' => 'اضافة الى الجدول',

    'export_dialog_title' => "تصدير البيانات",
    'export_dialog_filename' => 'اسم الملف',
    'export_dialog_help_filename' => 'يمكنك تغيير اسم الملف لما تراه مناسبا',
    'export_dialog_maxdata' => "اكبر قيمة",
    'export_dialog_help_maxdata' => 'اقصى حد لعمليات التصدير في الجسة : 100,000 عملية',
    'export_dialog_columns' => 'اعمدة',
    'export_dialog_format_export' => 'تنسيق التصدير',
    'export_dialog_show_advanced' => 'خيارات التصدير المتقدمة',
    'export_dialog_page_size' => 'مقاس الصفحة',
    'export_dialog_set_default' => 'تعيين كحجم افتراضي لمقاسات الصفحات',
    'export_dialog_page_orientation' => 'اتجاه الصفحة',

    'import_page_title' => 'استيراد :module',
    'dashboard_default_text' => 'مرحبا بك في شاشة :appname',
    'form_back_to_list' => 'العودة إلى قائمة البيانات :module',
    'not_logged_in' => 'لم تقم بتسجيل الدخول !',
    'menu_navigation' => "التنقل",
    'table_data_not_found' => "لا توجد بيانات متوفرة",
    "notice_delete_file_upload" => "* يجب حذف الملف الموجود قبل تحميل ملف آخر.",
    "file_broken" => "الملف معطوب ، فضلا احذف الملف واعد المحاولة .",

    'denied_access' => 'عفوا لاتملك الصلاحيات اللازمة للوصول لهذه الصفحة !',
    'denied_update' => 'عفوا لاتملك الصلاحيات اللازمة لتحديث البيانات !',
    'denied_create' => 'عفوا لاتملك الصلاحيات اللازمة لإنشاء بيانات جديدة !',
    'denied_delete' => 'عفوا لاتملك الصلاحيات اللازمة لحذف البيانات !',

    'user_image' => 'الصورة الرمزية للمستخدم',
    'online' => 'متصل',
    'controller_route_404' => 'لم يتم العثور على الرابط المطلوب',
    'home' => 'الرئيسية',
    'Notifications' => 'Notifications',
    'Privileges' => 'السماحيات',
    'Privileges_Roles' => 'صلاحيات الوصول',
    'Add_New_Privilege' => 'اضافة صلاحية',
    'List_Privilege' => 'عرض الصلاحيات',
    'add_user' => 'اضافة مستخدم',
    'List_users' => 'عرض المستخدمين',
    'Menu_Management' => 'ادارة القوائم',
    'Add_New_Setting' => 'اضافة اعدادات',
    'Add_New_Module' => 'اضافة تطبيق',
    'List_Module' => 'عرض التطبيقات',
    'Add_New_Statistic' => 'اضافة احصائيات',
    'List_Statistic' => 'عرض الاحصائيات',
    'Add_New_API' => 'اضافة API',
    'API_Generator' => 'انشاء API',
    'Statistic_Builder' => 'الاحصائيات والرسوم البيانية',
    'Module_Generator' => 'تطبيقات النظام',
    'settings' => 'اعدادات النظام',
    'Users_Management' => 'ادارة المستخدمين',
    'list_API' => 'عرض API',
    'Generate_Screet_Key' => 'انشاء مفتاح',
    'Add_New_Email' => 'اضافة قالب جديد',
    'List_Email_Template' => 'عرض القوالب',
    'Email_Templates' => 'قوالب البريد الإلكتروني',
    'Log_User_Access' => 'سجلات النظام',
    'SUPERADMIN' => 'مدير النظام ',
    'Module_Status' => 'حالة التطبيقات',
    'labels_translation' => 'الترجمات',
    'pages_and_forms' => 'باني الصفحات والنماذج',

    'click_here' => 'اضغط هنا ',

    /*
     * this is for html direction to use in html and css classes like :
     * pull-left , pull-right , text-right ...
     * to make it easy to use the the view for rtl langs .
     * unless your language use right-to-left direction , you should keep it as it is :
     */
    'right' => 'left',
    'left' => 'right',

    'all_rights_reserved' => 'كافة الحقوق محفوظة',
    'copyright' => 'حقوق النسخ',
    'powered_by' => 'انشئ بواسطة',

    'notification_you_have' => 'لديك',
    'notification_notification' => 'تنبيهات',
    'notification_new' => 'لديك تنبيه جديد',

    'login_register_style' => 'شاشة الدخول والتسجيل',
    'email_setting' => 'اعدادات البريد',
    'application_setting' => 'اعدادات عامة',

    // table filter & sort
    'filter_select_operator_type' => 'اختر نوع العملية',
    'filter_ascending' => 'تصاعدي',
    'filter_descending' => 'تنازلي',
    'filter_equal_to' => '=(يساوي لـ)',
    'filter_like' => 'مثل',
    'filter_not_like' => 'ليس مثل',
    'filter_greater_than_or_equal' => '>>= (اكبر من او يساوي)',
    'filter_less_than_or_equal' => '<= (اصغر من او يساوي)',
    'filter_less_than' => '< (اقل من)',
    'filter_greater_than' => '> (اكبر من)',
    'filter_not_equal_to' => '!= (لا يساوي لـ)',
    'filter_in' => 'ضمن',
    'filter_not_in' => 'ليس ضمن',
    'filter_between' => 'بين',
    'filter_empty_or_null' => 'Empty ( or Null)',
    'filter_sort_ascending' => 'فرز تصاعدي',
    'filter_sort_descending' => 'فرز تنازلي',
    'filter_eg' => 'مثال',
    'filter_lorem_ipsum' => 'ابجدي',
    'filter_lorem_ipsum_dolor_sit' => ' Lorem,Ipsum,Dolor Sit',
    'filter_search' => 'بحث',
    'filter_from' => 'من',
    'filter_to' => 'إلى',
    'filter_sorting' => 'Sorting',
    // confirmation
    'confirmation_yes' => 'نعم!',
    'confirmation_no' => 'لا',

    //filemanager
    'chose_an_image' => 'اختر صورة ',
    'chose_an_file' => 'اختر ملف ',

    // privilege
    'privileges_name' => 'اسم الصلاحية',
    'privileges_super_admin' => 'مدير النظام',
    'privileges_standart_user' => 'مستخدم',
    'privileges_ID' => 'م',
    'set_as_superadmin' => 'تعيين كمدير للنظام',
    'chose_theme_color_select' => '** اختر لون لوحة التحكم',
    'chose_theme_color' => ' لون لوحة التحكم',
    'privileges_configuration' => 'اعدادات الصلاحيات',
    'privileges_module_list_no' => 'لا.',
    'privileges_module_list_mod_names' => 'اسم النظام',
    'privileges_module_list_view' => 'عرض',
    'privileges_module_list_create' => 'انشاء',
    'privileges_module_list_read' => 'قراءة',
    'privileges_module_list_update' => 'تحديث',
    'privileges_module_list_delete' => 'حذف',

    //forms & landing pages
    'Pages' => 'الصفحات',
    'Forms' => 'النماذج',

    //datamodal
    'datamodal_select' => 'اختيار',
    'datamodal_search_and_enter' => 'البحث ...',
    'datamodal_enter_to_search' => 'اضفط ادخال للبحث',
    'datamodal_browse_data' => 'استعراض البيانات',
    'datamodal_browse_file' => 'استعراض الملف',

    //child
    'table_detail' => 'تفاصيل الجدول',
    'your_file_size_is_too_big' => 'حجم الملف كبير جدا',
    'save_changes' => 'حفظ التغييرات',
    'please_complete_the_form' => 'فضلا اكمل كافة حقول النموذج !',
    'this_field_is_required' => 'الحقل اجباري',
    'text_form' => 'نموذح',
    "your_file_extension_is_not_allowed " => "امتداد الملف غير مسموح به !",

    # Labels
    'ID' => 'ID',
    'Name' => 'الاسم',
    'Title' => 'العنوان',
    'Type' => 'النوع',
    'Email' => 'البريد الالكتروني',
    'Privilege' => 'السماحيات',
    'Photo' => 'الصورة',
    'Send To' => 'ارسال الى',
    'Response' => 'الرد',
    'active' => 'فعال',
    'Description' => 'الوصف',
    'Url' => 'عنوان url',
    'Send Email To', 'ارسال البريد الالكتروني الى',
    'Applications' => 'Applications',
    'Superadmin' => 'مدير النظام ',
    'Module' => 'التطبيق',
    'Additional Path' => 'المسار إضافي',
    'Icon' => 'الأيقونة',
    'Color' => 'اللون',
    'Active' => 'فعال',
    'InActive' => 'غير فعال',
    'Inactive' => 'غير فعال',
    'Dashboard' => 'الرئيسية',
    'Add Menu' => 'اضافة قائمة',
    'Helper Text' => 'النص المساعد',
    'Password' => 'كلمة السر',
    'Password Confirmation' => 'تأكيد كلمة السر',
    'Group' => 'المجموعة',
    'Label' => 'الوسم',
    'label' => 'الوسم',
    'Application Name' => 'اسم التطبيق',
    'Default Paper Print Size' => 'حجم طباعة الورق الافتراضي',
    'Logo' => 'اللوغو',
    'Path' => 'المسار',
    'Table' => 'الجدول',
    'Default Image ' => 'الصورة الافتراضية',
    'Activate Notifications' => 'تفعيل الاشعارات',
    'Login Background Color' => 'لون خلفية تسجيل الدخول',
    'Login Font Color' => 'لون خط تسجيل الدخول',
    'Login Background Image' => 'صورة خلفية تسجيل الدخول',
    'compression_quality' => 'هذا الحقل يحدد جودة الصورة بعد الرفع',
    'Template Name' => 'اسم القالب',
    'Content' => 'المحتوى',
    'Subject' => 'الموضوع',
    'From Name' => 'اسم المرسل',
    'From Email' => 'البريد الالكتروني للمرسل',
    'IP Address' => 'عنوان  IP',
    'Time Access' => 'وقت وقوع الحدث',
    'User' => 'المستخدم',
    'Row Type' => 'نوع السطر',
    'Fields' => 'الحقول',
    'required' => 'مطلوب',
    'Unique' => 'قيمة فريدة',
    'values' => 'القيم',
    'Slug' => 'ال Slug',
    'Module Slug' => 'ال slug  الخاصة بالموديول',
    'Response Message' => 'رسالة الرد',
    'Is Rtl' => 'تدعم ال Rtl',
    'Is Template' => 'نموذج ؟',
    'Menu Order' => 'ترتيب القوائم',
    'Module Name' => 'اسم الموديول',
    'Protected' => 'الحماية',
    'Module Information' => 'معلومات الموديول',
    'Save Module' => 'حفظ الموديول',
    'Step 1' => 'الخطوة 1',
    'Step 2' => 'الخطوة 2',
    'Step 3' => 'الخطوة 3',
    'Step 4' => 'الخطوة 4',
    'Table Display' => 'عرض الجدول',
    'Column' => 'العمود',
    'Width' => 'العرض',
    'Image' => 'صورة',
    'Download' => 'تحميل',
    'Switch' => 'سويتش',
    'Str Limit' => 'حدود السلسلة',
    'Form Display' => 'عرض النموذج',
    'Configuration' => 'الاعدادات',
    'Action' => 'الاجراء',
    'Optional' => 'اختياري',
    'Validation' => 'التحقق',
    'Options' => 'خيارات',
    'Title Field Candidate' => 'عنوان الحقل المرشح',
    'Limit Data' => 'حدود البيانات',
    'Order By' => 'ترتيب حسب',
    'Show Button Table Action' => 'اظهار زر الاجراءات',
    'Show Bulk Action Button' => 'اظهار زر ال bulk',
    'Show Button Filter & Sorting' => 'اظهار زر الترتيب والفلترة',
    'Show Button Import' => 'اظهار زر الاستيراد',
    'Show Button Export' => 'اظهار زر التصدير',
    'Show Button Add' => 'اظهار زر الاضافة',
    'Show Button Edit' => 'اظهار زر التعديل',
    'Show Button Delete' => 'اظهار زر الحذف',
    'Show Button Detail' => 'اظهار زر التفاصيل',
    'Show Button Show Data' => 'اظهار زر اظهار البيانات',
    'Sortable' => 'قابلية الترتيب',
    'Global Privilege' => 'سماحية عامة',
    'Button Action Style' => 'الستايل الخاص بزر الاجراء',
    'Cc Email' => 'ال Cc Email',
    'Clear All Logs' => 'حذف كافة الجلسات',
    'filter_rows_total' => 'اجمالي الأسطر',
    'Menu Management' => 'ادارة القوائم',
    'Translation' => 'الترجمة',
    'Key' => 'المفتاح',
    'enter_key' => 'أدخل المفتاح',
    'enter_value' => 'أدخل القيمة',
    'English' => 'الانجليزية',
    'Arabic' => 'العربية',
    'Add' => 'اضافة',
    'Edit' => 'تعديل',
    'Delete' => 'حذف',
    'clear_logs' => 'حذف جميع السجلات',
    'def_img_quality' => 'يحدد هذا الحقل جودة الصورة بعد التحميل (ستنخفض جودة الصورة كلما قللنا من قيمة الإدخال والعكس صحيح)',
    'language_setting' => 'اعدادات اللغة',
    'activate_tow_languages' => 'تفعيل اللغتين العربية والانكليزية في ال CMS',
    'default_language' => 'هذا الحقل يحدد اللغة الافتراضية المعتمدة في التطبيق',
    'block_users_setting' => 'اعدادات الحظر',
    'block_ip_in_hours_helper' => 'هذا الحقل يحدد المدة الزمنية التي سيتم حظر ال IP بها بعد قيامه بتجاوز عدد محاولات التسجيل الفاشلة مقدرة بالساعات',
    'max_failed_login_trying_helper' => 'هذا الحقل يحدد العدد الأعظمي لمحاولات تسجيل الدخول الفاشلة',
    'login_block_msg' => 'عذرًا، يبدو أنك تجاوزت الحد الأقصى لمحاولات تسجيل الدخول. لأسباب أمنية، تم حظرك مؤقتًا. يرجى المحاولة مرة أخرى لاحقًا أو الاتصال بفريق الدعم إذا كنت بحاجة إلى مساعدة. شكرًا لك.',
    'search_for_key_values' => 'ابحث عن كلمة أو مفتاح',
    'activate_label' => ' تفعيل العمود',
    'deactivate_label' => 'الغاء تفعيل العمود ',
    'has_images' => 'يحوي صور ؟',
    'model_images' => 'الصور',

    'file_support_ext' => 'الملف يدعم فقط اللاحقات (jpg,png,gif) وأقصى حجم تحميل 10 MB',
    'notifications_activity' => 'يحدد هذا الحقل ما إذا كانت الإشعارات مفعلة أم لا (غير مفعلة افتراضيًا)',
    'enter_lang_values' => 'أدخل القيم',
    'enter_lang_key' => 'أدخل المفتاح',
    'Website_Languages' => 'لغات الموقع الالكتروني',

    // setting labels
    'email_sender' => 'Email Sender',
    'mail_driver' => 'Mail Driver',
    'smtp_host' => 'SMTP Host',
    'smtp_port' => 'SMTP Port',
    'smtp_username' => 'SMTP Username',
    'smtp_password' => 'SMTP Password',
    'application_name' => 'اسم التطبيق',
    'default_paper_size' => 'حجم طباعة الورق الافتراضي',
    'uploaded_default_image' => 'الصورة الافتراضية',
    'image_compression_value' => 'قيمة ضغط الصورة',
    'favicon' => 'Favicon',
    'api_debug_mode' => 'API Debug Mode',
    'google_api_key' => 'Google API Key',
    'google_fcm_key' => 'Google FCM Key',
    'activate_notifications' => 'تفعيل الإخطارات',
    'default_cms_language' => 'لغة CMS الافتراضية',
    'block_ip_in_hours' => 'حظر عنوان IP',
    'max_failed_login_trying' => 'الحد الأقصى',
    'no_use_cms_prefix' => 'يرجى عدم استخدام اللاحقة cms_* في اسماء الجداول الخاصة بك',
    'module_slug_expression' => 'فضلا استخدم فقط المحارف الابجدية بدون فراغات أو محارف مميزة _ and or',
    'ask_create_modules_menu' => 'اضافة قائمة للموديول الحالي أيضا',
    'create_modules_menu' => 'اذا تم الضغط على هذا الخيار فسوف يتم انشاء قائمة للموديول الحالي',
    'title_field_candidate' => 'عنوان الحقل المرشح',

    'successfully_save_settings' => 'تم حفظ الاعدادات الخاصة بك بنجاح !',
    'Module_Blocked_IPS' => 'قائمة الحظر',

    'Backup_Restore_DB' => 'النسخ الاحتياطي & استعادة قواعد البيانات',
    'restore_db' => 'استعادة',
    'delete_db' => 'حذف',
    'make_backup' => 'اضافة نسخ احتياطي جديد',
    'recaptcha_site_key' => 'مفتاح الموقع الالكتروني الخاص ب reCAPTCHA',
    'recaptcha_secret_key' => 'المفتاح السري الخاص ب reCAPTCHA',
    'success_add_backup' => 'تم اضافة النسخ الاحتياطي بنجاح',
    'error_add_backup' => 'حدث خطأ ما أثناء اضافة النسخ الاحتياطي !',
    'action_set_seo' => 'اضافة SEO',
    'backup_file_size' => 'الحجم',
    'reCAPTCHA_setting' => 'reCaptcha اعدادات',

    'alert_recaptcha' => 'حدث خطأ في reCAPTCHA. الرجاء معاودة المحاولة في وقت لاحق',
    'menus_configuration'=>'إعدادات القوائم',

];
